# Generated by Django 4.1.3 on 2022-12-01 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedAviacion', '0003_registrovuelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrovuelo',
            name='observacion',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
